/// Flutter icons StcIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StcIcons
///      fonts:
///       - asset: fonts/StcIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class StcIcons {
  StcIcons._();

  static const _kFontFam = 'StcIcons';
  static const String? _kFontPkg = null;

  static const IconData search = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fries_bar = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_arrow = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
